{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cd41a8d5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Local\\Temp\\4\\ipykernel_10008\\3188354473.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\__init__.py\", line 39, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Local\\Temp\\4\\ipykernel_10008\\3188354473.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Local\\Temp\\4\\ipykernel_10008\\3188354473.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\ops\\__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\computation\\expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\computation\\check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\site-packages\\numexpr\\__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Local\\Temp\\4\\ipykernel_10008\\3188354473.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\arrays\\masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\core\\nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"C:\\Users\\doseguera\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Program Files\\Anaconda\\Lib\\site-packages\\bottleneck\\__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "import os\n",
    "import telegram\n",
    "from datetime import datetime, timedelta\n",
    "from dotenv import load_dotenv\n",
    "from pymongo import MongoClient\n",
    "from pymongo.errors import ConnectionFailure\n",
    "import asyncio\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a9c4f7a9-14f9-427b-a5f4-384bea846f97",
   "metadata": {},
   "outputs": [],
   "source": [
    "load_dotenv();"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "98df0216-3a39-4fb7-97ed-6e09802a67da",
   "metadata": {},
   "outputs": [],
   "source": [
    "BOT_TOKEN = os.getenv('BOT_TOKEN')\n",
    "CHAT_ID_1 = os.getenv('CHAT_ID_1')\n",
    "CHAT_ID_2 = os.getenv('CHAT_ID_2')\n",
    "CHAT_ID_3 = os.getenv('CHAT_ID_3')\n",
    "API_KEY = os.getenv('API_KEY')\n",
    "THRESHOLD_MS = int(os.getenv('THRESHOLD_MS'))\n",
    "THRESHOLD_DUPLICATES = int(os.getenv('THRESHOLD_DUPLICATES'))\n",
    "with open(os.getenv('MEAN_RECORDS_JSON_MONGO'), 'r') as meanRecordsByHour:\n",
    "    meanStdRecords = json.load(meanRecordsByHour)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "411d025b-68fd-4bdf-8c85-dc06c34af509",
   "metadata": {},
   "outputs": [],
   "source": [
    "USERNAME = os.getenv('USER_MONGO')\n",
    "PASSWORD = os.getenv('PASSWORD_MONGO')\n",
    "HOST = os.getenv('HOST_MONGO')\n",
    "PORT = int(os.getenv('PORT_MONGO'))\n",
    "DATABASE = os.getenv('DATABASE_MONGO')\n",
    "COLLECTION = os.getenv('COLLECTION_MONGO')\n",
    "CA_CERT = os.getenv('CA_CERT_MONGO')\n",
    "CLIENT_CERT = os.getenv('CLIENT_CERT_MONGO')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2e47b46f",
   "metadata": {},
   "outputs": [],
   "source": [
    "bot = telegram.Bot(token=BOT_TOKEN)\n",
    "\n",
    "async def send_telegram_message(message, chat_semaphore):\n",
    "    '''\n",
    "    Envía un mensaje de alerta a Telegram (asincrónico).\n",
    "    '''\n",
    "    try:\n",
    "        await bot.send_message(chat_id=chat_semaphore, text=message)\n",
    "        print(f\"Mensaje enviado a Telegram: {message}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error al enviar mensaje a Telegram: {e}\")\n",
    "def connect_to_mongo():\n",
    "    '''\n",
    "    Establece la conexión a MongoDB y devuelve el cliente y la colección.\n",
    "    '''\n",
    "    try:\n",
    "        client = MongoClient(\n",
    "            host=f\"mongodb+srv://{HOST}/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS&w=majority&appName=MONGO-PROD-RPV\",\n",
    "            tls=True,\n",
    "            tlsCertificateKeyFile=CLIENT_CERT,\n",
    "            serverSelectionTimeoutMS=5000,\n",
    "            socketTimeoutMS=40000,\n",
    "            connectTimeoutMS=300000\n",
    "        )\n",
    "        db = client[DATABASE]\n",
    "        collection = db[COLLECTION]\n",
    "        return collection\n",
    "    except ConnectionFailure as e:\n",
    "        print(\"Failed to connect to MongoDB:\", e)\n",
    "        return None\n",
    "\n",
    "def fetch_data_from_mongo(collection, required_fields, time_field=\"requestTime\", time_range_minutes=10):\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    Extrae datos de MongoDB aplicando un filtro basado en los últimos 10 minutos\n",
    "\n",
    "    a partir de la hora actual de la computadora, seleccionando las columnas necesarias.\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "        max_time =  datetime.now()\n",
    "        start_time = max_time - timedelta(minutes=time_range_minutes)\n",
    "        end_time = max_time\n",
    "        print(\"La hora de la computadora es:\",end_time)\n",
    "        start_time = end_time - timedelta(minutes=time_range_minutes)\n",
    "        print(f\"Consultando datos entre {start_time} y {end_time}\")\n",
    "        query = {'requestTime': {\"$gte\": start_time, \"$lte\": end_time}}\n",
    "        print(\"Consulta MongoDB:\", query)\n",
    "        q = collection.find(query)\n",
    "        documents = list(q)\n",
    "        print(f\"Datos encontrados: {len(documents)} documentos\")\n",
    "        return documents\n",
    "    except Exception as e:\n",
    "        print(f\"Error al extraer datos desde MongoDB: {e}\")\n",
    "        return []\n",
    " \n",
    " \n",
    " \n",
    "def flatten_json(json_object, parent_key='', sep='_'):\n",
    "    \"\"\"\n",
    "    Aplana un JSON anidado para convertirlo en una estructura plana.\n",
    "    \"\"\"\n",
    "    items = []\n",
    "    if isinstance(json_object, dict):\n",
    "        for k, v in json_object.items():\n",
    "            new_key = f\"{parent_key}{sep}{k}\" if parent_key else k\n",
    "            if isinstance(v, dict):\n",
    "                items.extend(flatten_json(v, new_key, sep=sep).items())\n",
    "            elif isinstance(v, list) and all(isinstance(i, (str, int, float)) for i in v):\n",
    "                items.append((new_key, ', '.join(map(str, v))))\n",
    "            elif isinstance(v, list):\n",
    "                for i, sub_item in enumerate(v):\n",
    "                    items.extend(flatten_json(sub_item, f\"{new_key}{sep}{i}\", sep=sep).items())\n",
    "            else:\n",
    "                items.append((new_key, v))\n",
    "    elif isinstance(json_object, list):\n",
    "        for i, sub_item in enumerate(json_object):\n",
    "            items.extend(flatten_json(sub_item, f\"{parent_key}{sep}{i}\", sep=sep).items())\n",
    "    return dict(items)\n",
    "\n",
    "async def analyze_service_status(df):\n",
    "    \"\"\"\n",
    "    Analiza el estado de servicio para detectar errores HTTP y envía alertas por cada tipo de error.\n",
    "    \"\"\"\n",
    "    total_rows = len(df)\n",
    "    if total_rows == 0:\n",
    "        message = \"¡ALERTA_ROJA__c_ciudadana! No hay datos para analizar.\"\n",
    "        await send_telegram_message(message, CHAT_ID_3)\n",
    "        return {\"failure_rate\": 0, \"total_rows_analyzed\": 0}\n",
    "    error_codes = [500, 401, 403, 404]  \n",
    "    error_counts = {}\n",
    "    for code in error_codes:\n",
    "        error_rows = df[df['responseCode'] == code]\n",
    "        error_counts[code] = len(error_rows)\n",
    "\n",
    "        if len(error_rows) == 1:\n",
    "            message = f\"¡ALERTA_AMARILLA__c_ciudadana! {len(error_rows)} consultas fallidas con error {code}.\"\n",
    "            print(message)\n",
    "            await send_telegram_message(message, CHAT_ID_2)\n",
    "        elif len(error_rows) > 1:\n",
    "            message = f\"¡ALERTA_ROJA_c_ciudadana! {len(error_rows)} consultas fallidas con error {code}.\"\n",
    "            print(message)\n",
    "            await send_telegram_message(message, CHAT_ID_3)\n",
    "\n",
    "    total_failures = sum(error_counts.values())\n",
    "    failure_rate = (total_failures / total_rows * 100) if total_rows > 0 else 0\n",
    " \n",
    "    return {\n",
    "        \"failure_rate\": failure_rate,\n",
    "        \"total_rows_analyzed\": total_rows,\n",
    "        \"error_counts\": error_counts,\n",
    "    }\n",
    " \n",
    "async def check_high_latency(df, column_name, threshold_ms):\n",
    "    threshold = float(threshold_ms)  \n",
    "    high_latency = df[df[column_name] > threshold]\n",
    " \n",
    "    if len(high_latency) == 1:\n",
    "        message = f\"¡ALERTA_AMARILLA_c_ciudadana! {len(high_latency)} consultas con latencia mayor a {threshold_ms} ms.\"\n",
    "        print(message)\n",
    "        await send_telegram_message(message, CHAT_ID_2)\n",
    "    elif len(high_latency)>1:\n",
    "        message = f\"¡ALERTA_ROJA_c_ciudadana! {len(high_latency)} consultas con latencia mayor a {threshold_ms} ms.\"\n",
    "        print(message)\n",
    "        await send_telegram_message(message, CHAT_ID_3)\n",
    "        \n",
    "    return len(high_latency)\n",
    " \n",
    "async def check_duplicate_locations(df, lat_column, lon_column, threshold, exclude_value=1):\n",
    "    df[lat_column] = pd.to_numeric(df[lat_column], errors='coerce')\n",
    "    df[lon_column] = pd.to_numeric(df[lon_column], errors='coerce')\n",
    " \n",
    "    filtered_df = df[(df[lat_column] != exclude_value) & (df[lon_column] != exclude_value)]\n",
    "    grouped = (\n",
    "        filtered_df.groupby([lat_column, lon_column])\n",
    "        .size()\n",
    "        .reset_index(name='count')\n",
    "    )\n",
    "    duplicates = grouped[grouped['count'] > threshold]\n",
    " \n",
    "    if not duplicates.empty:\n",
    "        message = f\"¡ALERTA_AMARILLA_c_ciudadana! {len(duplicates)} ubicaciones con más de {threshold} solicitudes.\"\n",
    "        print(message)\n",
    "        await send_telegram_message(message, CHAT_ID_2)\n",
    " \n",
    "    return duplicates\n",
    " \n",
    "async def check_invalid_api_keys(df, column_name, valid_api_key):\n",
    "    invalid_keys = df[df[column_name] != valid_api_key]\n",
    " \n",
    "    if not invalid_keys.empty:\n",
    "        message = f\"¡ALERTA_AMARILLA_c_ciudadana! {len(invalid_keys)} registros contienen apiKey inválida.\"\n",
    "        print(message)\n",
    "        await send_telegram_message(message, CHAT_ID_2)\n",
    " \n",
    "    return invalid_keys\n",
    "\n",
    "async def counts_records(df, meanStdRecords, last_time_sub, n_minutes, nombreMicroservicio = 'CONSULTA_CIUDADANA'):   \n",
    "    '''\n",
    "    Counts how many records dataframe has and determines if the count is normal\n",
    "    Args:\n",
    "        regularizationFrame (DataFrame): the dataframe to search\n",
    "        meanStdRecords (dict): Dictionary with traffic count averages and standard deviations by day and hour\n",
    "        lastTimeSub (string): Day and hour of comparation\n",
    "        days_of_week : Days of week list\n",
    "        n_minutes: Difference between the older record and the newer record \n",
    "    Returns:\n",
    "    '''\n",
    "    \n",
    "    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']\n",
    "\n",
    "    date_object = datetime.strptime(str(last_time_sub), \"%Y-%m-%d %H:%M:%S.%f\")\n",
    "    \n",
    "    day_name = date_object.strftime(\"%A\")  \n",
    "    hour = date_object.hour \n",
    "    \n",
    "    meanStd = meanStdRecords[f'{day_name}_{hour}']\n",
    "    \n",
    "    std = meanStd['std']\n",
    "    mean = meanStd['mean']\n",
    "\n",
    "    nMinutesProportion = n_minutes/60\n",
    "    \n",
    "    if std/mean >0.6:\n",
    "        maxRecords = nMinutesProportion*(mean + 2*std)\n",
    "        minRecords = nMinutesProportion*(mean - 2*std)\n",
    "    else:\n",
    "        maxRecords = nMinutesProportion*(mean + 1.5*std)\n",
    "        minRecords = nMinutesProportion*(mean - 1.5*std)\n",
    "        \n",
    "    if minRecords < 0:\n",
    "        minRecords = 0\n",
    "    \n",
    "    recordsNumber = df.shape[0]\n",
    "    \n",
    "    if recordsNumber> maxRecords and recordsNumber/maxRecords < 2:\n",
    "        message = f'Alerta media {nombreMicroservicio} de cantidad de registros. Se registran más de {maxRecords} para la hora: {recordsNumber}'\n",
    "        await send_telegram_message(message, CHAT_ID_2)\n",
    "    elif recordsNumber/maxRecords >= 2:\n",
    "        message = f'Alerta alta {nombreMicroservicio} de cantidad de registros. Se registran más de {maxRecords} para la hora: {recordsNumber}'\n",
    "        await send_telegram_message(message, CHAT_ID_3)\n",
    "    else:\n",
    "        message = f'Sin alerta {nombreMicroservicio}. El tráfico no rebasa la cota superior.'\n",
    "        await send_telegram_message(message, CHAT_ID_1)\n",
    "        \n",
    "    if recordsNumber< minRecords and minRecords/recordsNumber < 2:\n",
    "        message = f'Alerta media {nombreMicroservicio} de cantidad de registros. Se registran menos de {minRecords} para la hora: {recordsNumber}'\n",
    "        await send_telegram_message(message, CHAT_ID_2)\n",
    "    elif minRecords/recordsNumber >= 2:\n",
    "        message = f'Alerta alta {nombreMicroservicio} de cantidad de registros. Se registran menos de {minRecords} para la hora: {recordsNumber}'\n",
    "        await send_telegram_message(message, CHAT_ID_3)\n",
    "    else:\n",
    "        message = f'Sin alerta {nombreMicroservicio}. El tráfico no rebasa la cota inferior.'\n",
    "        await send_telegram_message(message, CHAT_ID_1) \n",
    " \n",
    "async def main():\n",
    "    collection = connect_to_mongo()\n",
    "    if collection is None:\n",
    "        await send_telegram_message(\"¡Alerta_ROJA_c_ciudadana! No se pudo conectar a MongoDB.\", CHAT_ID_3)\n",
    "        return\n",
    " \n",
    "    #required_fields = [\"responseTime\", \"requestTime\", \"responseCode\", \"latitude\",\"longitude\", \"apiKey\"]\n",
    "    required_fields = [\"responseTime\", \"requestTime\", \"responseCode\", \"apiKey\"]\n",
    "    \n",
    "    raw_data = fetch_data_from_mongo(collection, required_fields=required_fields, time_field=\"responseTime\", time_range_minutes=10)\n",
    "    if not raw_data:\n",
    "        await send_telegram_message(\"¡Alerta_ROJA_c_ciudadana! No se encontraron datos en los últimos 10 minutos (relativos).\", CHAT_ID_3)\n",
    "        return\n",
    "    flattened_data = [flatten_json(doc) for doc in raw_data]\n",
    "    df = pd.DataFrame(flattened_data)\n",
    "    last_time_sub = df['responseTime'].iloc[-1] \n",
    " \n",
    "    columns_to_convert = ['requestTime', 'responseTime']\n",
    "    for col in columns_to_convert:\n",
    "        if col in df.columns:\n",
    "            df[col] = pd.to_datetime(df[col])\n",
    "        else:\n",
    "            print(f\"Advertencia: La columna '{col}' no está presente en los datos.\")\n",
    " \n",
    "    if 'requestTime' in df.columns and 'responseTime' in df.columns:\n",
    "        df['tie_comu_ini'] = (df['responseTime'] - df['requestTime']).dt.total_seconds() * 1000\n",
    "    else:\n",
    "        await send_telegram_message(\"¡Alerta_AMARILLA_c_ciudadana! Error: No se pueden calcular tiempos porque faltan 'requestTime' o 'responseTime'.\", CHAT_ID_2)\n",
    "        return\n",
    " \n",
    "    total_consultas = len(df)\n",
    "    await send_telegram_message(f\"¡Alerta_VERDE_c_ciudadana! Total de consultas evaluadas: {total_consultas}\", CHAT_ID_1)\n",
    " \n",
    "    await analyze_service_status(df)\n",
    "    await check_high_latency(df, column_name='tie_comu_ini', threshold_ms=THRESHOLD_MS)\n",
    "    if 'latitude' in list(df.columns) and 'longitude' in list(df.columns):\n",
    "        await check_duplicate_locations(\n",
    "            df, lat_column='latitude', lon_column='longitude', threshold=THRESHOLD_DUPLICATES\n",
    "        )\n",
    "    await check_invalid_api_keys(df, column_name='apiKey', valid_api_key=API_KEY)\n",
    "    await counts_records(df, meanStdRecords, last_time_sub, 10)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "87fd5de9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "La hora de la computadora es: 2024-12-06 03:31:53.166593\n",
      "Consultando datos entre 2024-12-06 03:21:53.166593 y 2024-12-06 03:31:53.166593\n",
      "Consulta MongoDB: {'requestTime': {'$gte': datetime.datetime(2024, 12, 6, 3, 21, 53, 166593), '$lte': datetime.datetime(2024, 12, 6, 3, 31, 53, 166593)}}\n",
      "Datos encontrados: 394 documentos\n",
      "Mensaje enviado a Telegram: ¡Alerta_VERDE_c_ciudadana! Total de consultas evaluadas: 394\n",
      "¡ALERTA_ROJA_c_ciudadana! 9 consultas fallidas con error 401.\n",
      "Mensaje enviado a Telegram: ¡ALERTA_ROJA_c_ciudadana! 9 consultas fallidas con error 401.\n",
      "¡ALERTA_ROJA_c_ciudadana! 7 consultas con latencia mayor a 1141 ms.\n",
      "Mensaje enviado a Telegram: ¡ALERTA_ROJA_c_ciudadana! 7 consultas con latencia mayor a 1141 ms.\n",
      "Mensaje enviado a Telegram: Sin alerta CONSULTA_CIUDADANA. El tráfico no rebasa la cota superior.\n",
      "Mensaje enviado a Telegram: Alerta media CONSULTA_CIUDADANA de cantidad de registros. Se registran menos de 446.09356111084094 para la hora: 394\n"
     ]
    }
   ],
   "source": [
    "#asyncio.run(main())\n",
    "while True:\n",
    "    await main()\n",
    "    time.sleep(600)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "010086a6-0edf-4a02-a497-1607f122bfc5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
